/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import visão.Suprimento.Distribuição_Tela;
import visão.Afastamento.Afastados;
import visão.Cancelamento.Cancelamento_Tela;
import visão.Afastamento.Inserir_Afastamento;
import visão.Cancelamento.Cancelamentos;
import visão.Professor.Professor_Tela;
import visão.Professor.Select_Professor;
import visão.Substituicao.Cadastro_Substituição;
import visão.Turma.Inserir_Disciplina;
import visão.Turma.Turma_Tela;
import visão.newpackage.Substituição;

/**
 *
 * @author Meus Documentos
 */
public class PáginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PáginaInicial
     */
    
    public PáginaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        painelExibição = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        adiciona_Curso = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        insere_Turma = new javax.swing.JMenuItem();
        insere_Disciplina = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        insere_Professor = new javax.swing.JMenuItem();
        prof_Alteracao = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        insere_Afastamento = new javax.swing.JMenuItem();
        todos_Afastados = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        insere_Suprimento = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        insere_Cancelamento = new javax.swing.JMenuItem();
        todos_Cancelamentos = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        insere_Substituicao = new javax.swing.JMenuItem();
        exibe_Substituicoes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout painelExibiçãoLayout = new javax.swing.GroupLayout(painelExibição);
        painelExibição.setLayout(painelExibiçãoLayout);
        painelExibiçãoLayout.setHorizontalGroup(
            painelExibiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelExibiçãoLayout.setVerticalGroup(
            painelExibiçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        jMenuItem3.setText("Fechar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem12.setText("Gerar Suprimento");
        jMenu1.add(jMenuItem12);

        jMenuItem13.setText("Gerar Cancelamento");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem14.setText("Gerar Substituição");
        jMenu1.add(jMenuItem14);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Configurações");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenu8.setText("Curso");

        adiciona_Curso.setText("Adicionar");
        adiciona_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiciona_CursoActionPerformed(evt);
            }
        });
        jMenu8.add(adiciona_Curso);

        jMenu5.add(jMenu8);

        jMenu7.setText("Turma");

        insere_Turma.setText("Nova Turma");
        insere_Turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insere_TurmaActionPerformed(evt);
            }
        });
        jMenu7.add(insere_Turma);

        insere_Disciplina.setText("Inserir Disciplina");
        insere_Disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insere_DisciplinaActionPerformed(evt);
            }
        });
        jMenu7.add(insere_Disciplina);

        jMenu5.add(jMenu7);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Professor");

        insere_Professor.setText("Cadastrar");
        insere_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insere_ProfessorActionPerformed(evt);
            }
        });
        jMenu2.add(insere_Professor);

        prof_Alteracao.setText("Visualizar Todos");
        prof_Alteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prof_AlteracaoActionPerformed(evt);
            }
        });
        jMenu2.add(prof_Alteracao);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Opções");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenu11.setText("Afastamento");

        insere_Afastamento.setText("Novo");
        insere_Afastamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insere_AfastamentoActionPerformed(evt);
            }
        });
        jMenu11.add(insere_Afastamento);

        todos_Afastados.setText("Visualizar Todos");
        todos_Afastados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todos_AfastadosActionPerformed(evt);
            }
        });
        jMenu11.add(todos_Afastados);

        jMenu6.add(jMenu11);

        jMenu4.setText("Suprimento");

        insere_Suprimento.setText("Novo");
        insere_Suprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insere_SuprimentoActionPerformed(evt);
            }
        });
        jMenu4.add(insere_Suprimento);

        jMenu6.add(jMenu4);

        jMenu9.setText("Cancelamento");

        insere_Cancelamento.setText("Novo");
        insere_Cancelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insere_CancelamentoActionPerformed(evt);
            }
        });
        jMenu9.add(insere_Cancelamento);

        todos_Cancelamentos.setText("Visualizar Todos");
        todos_Cancelamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todos_CancelamentosActionPerformed(evt);
            }
        });
        jMenu9.add(todos_Cancelamentos);

        jMenu6.add(jMenu9);

        jMenu10.setText("Substituição");

        insere_Substituicao.setText("Novo");
        insere_Substituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insere_SubstituicaoActionPerformed(evt);
            }
        });
        jMenu10.add(insere_Substituicao);

        exibe_Substituicoes.setText("Visualizar Substituições");
        exibe_Substituicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibe_SubstituicoesActionPerformed(evt);
            }
        });
        jMenu10.add(exibe_Substituicoes);

        jMenu6.add(jMenu10);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 312, Short.MAX_VALUE))
            .addComponent(painelExibição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelExibição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void insere_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insere_ProfessorActionPerformed
        // TODO add your handling code here:
        new Professor_Tela().setVisible(true);

    }//GEN-LAST:event_insere_ProfessorActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new Cancelamento_Tela().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
        System.out.println("ok");
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void adiciona_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiciona_CursoActionPerformed
        // TODO add your handling code here
        new Curso_Tela().setVisible(true);
    }//GEN-LAST:event_adiciona_CursoActionPerformed

    private void insere_TurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insere_TurmaActionPerformed
        // TODO add your handling code here:
        new Turma_Tela().setVisible(true);
    }//GEN-LAST:event_insere_TurmaActionPerformed

    private void insere_DisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insere_DisciplinaActionPerformed
        // TODO add your handling code here:
        new Inserir_Disciplina().setVisible(true);
    }//GEN-LAST:event_insere_DisciplinaActionPerformed

    private void prof_AlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prof_AlteracaoActionPerformed
        // TODO add your handling code here:
        new Select_Professor().setVisible(true);
    }//GEN-LAST:event_prof_AlteracaoActionPerformed

    private void insere_AfastamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insere_AfastamentoActionPerformed
        // TODO add your handling code here:
        new Inserir_Afastamento().setVisible(true);
    }//GEN-LAST:event_insere_AfastamentoActionPerformed

    private void insere_SuprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insere_SuprimentoActionPerformed
        // TODO add your handling code here:
        new Distribuição_Tela().setVisible(true);
    }//GEN-LAST:event_insere_SuprimentoActionPerformed

    private void insere_CancelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insere_CancelamentoActionPerformed
        // TODO add your handling code here:
        new Cancelamento_Tela().setVisible(true);
    }//GEN-LAST:event_insere_CancelamentoActionPerformed

    private void insere_SubstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insere_SubstituicaoActionPerformed
        // TODO add your handling code here:
        new Substituição().setVisible(true);
    }//GEN-LAST:event_insere_SubstituicaoActionPerformed

    private void todos_AfastadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todos_AfastadosActionPerformed
        // TODO add your handling code here:
        new Afastados().setVisible(true);
    }//GEN-LAST:event_todos_AfastadosActionPerformed

    private void todos_CancelamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todos_CancelamentosActionPerformed
        // TODO add your handling code here:
        new Cancelamentos().setVisible(true);
    }//GEN-LAST:event_todos_CancelamentosActionPerformed

    private void exibe_SubstituicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibe_SubstituicoesActionPerformed
        // TODO add your handling code here:
        new Cadastro_Substituição().setVisible(true);
    }//GEN-LAST:event_exibe_SubstituicoesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       new PáginaInicial().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adiciona_Curso;
    private javax.swing.JMenuItem exibe_Substituicoes;
    private javax.swing.JMenuItem insere_Afastamento;
    private javax.swing.JMenuItem insere_Cancelamento;
    private javax.swing.JMenuItem insere_Disciplina;
    private javax.swing.JMenuItem insere_Professor;
    private javax.swing.JMenuItem insere_Substituicao;
    private javax.swing.JMenuItem insere_Suprimento;
    private javax.swing.JMenuItem insere_Turma;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel painelExibição;
    private javax.swing.JMenuItem prof_Alteracao;
    private javax.swing.JMenuItem todos_Afastados;
    private javax.swing.JMenuItem todos_Cancelamentos;
    // End of variables declaration//GEN-END:variables
}
