/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.table.TableColumn;

/**
 *
 * @author Meus Documentos
 */
public class PáginaInicial extends javax.swing.JFrame {
private String[]linha={"tiago","maria","joão"};
    /**
     * Creates new form PáginaInicial
     */
    public PáginaInicial(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    PáginaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        insTurma = new javax.swing.JMenuItem();
        insereProf = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        editDisciplina = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        consulta_Prof = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/turma.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1200, 700));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 300));

        jMenu1.setText("Arquivo");

        jMenuItem3.setText("Fechar");
        jMenu1.add(jMenuItem3);

        jMenuItem12.setText("Gerar Suprimento");
        jMenu1.add(jMenuItem12);

        jMenuItem13.setText("Gerar Cancelamento");
        jMenu1.add(jMenuItem13);

        jMenuItem14.setText("Gerar Substituição");
        jMenu1.add(jMenuItem14);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Inserir");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Disciplinas");
        jMenu5.add(jMenuItem4);

        insTurma.setText("Turmas");
        insTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insTurmaActionPerformed(evt);
            }
        });
        jMenu5.add(insTurma);

        insereProf.setText("Professores");
        insereProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insereProfActionPerformed(evt);
            }
        });
        jMenu5.add(insereProf);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Editar");

        editDisciplina.setText("Disciplinas");
        editDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDisciplinaActionPerformed(evt);
            }
        });
        jMenu2.add(editDisciplina);

        jMenuItem8.setText("Turmas");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Professor(es)");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        consulta_Prof.setText("Consultar");
        consulta_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_ProfActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Disciplinas");
        consulta_Prof.add(jMenuItem2);

        jMenuItem10.setText("Turmas");
        consulta_Prof.add(jMenuItem10);

        jMenuItem11.setText("Professor(es)");
        consulta_Prof.add(jMenuItem11);

        jMenuBar1.add(consulta_Prof);

        jMenu4.setText("Opções");

        jMenuItem15.setText("Enviar Suprimento");
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("Enviar Cancelamento");
        jMenu4.add(jMenuItem16);

        jMenuItem17.setText("Enviar Substituição");
        jMenu4.add(jMenuItem17);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 129, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void insereProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insereProfActionPerformed
        // TODO add your handling code here:
        Professor_Tela prof=new Professor_Tela();
        prof.setVisible(true);
    }//GEN-LAST:event_insereProfActionPerformed

    private void insTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insTurmaActionPerformed
        // TODO add your handling code here:
        Turma_Tela tur=new Turma_Tela();
        tur.setVisible(true);
        
    }//GEN-LAST:event_insTurmaActionPerformed

    private void consulta_ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_ProfActionPerformed
        // TODO add your handling code here:
//        Cae_Profs cae=new Cae_Profs();
//        cae.setVTurma_Telae(true);
       
    }//GEN-LAST:event_consulta_ProfActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Cae_Profs cp=new Cae_Profs();
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void editDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDisciplinaActionPerformed
        // TODO add your handling code here:
        Disciplina_Tela d=new Disciplina_Tela();
        d.setVisible(true);
        
    }//GEN-LAST:event_editDisciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PáginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                PáginaInicial dialog = new PáginaInicial(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu consulta_Prof;
    private javax.swing.JMenuItem editDisciplina;
    private javax.swing.JMenuItem insTurma;
    private javax.swing.JMenuItem insereProf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
