/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visão.testesExtends;

import visão.Turma_Tela;

/**
 *
 * @author Meus Documentos
 */
public class Grade_Extensão_Turma extends Turma_Tela {

    /**
     * Creates new form Grade_Extensão_Turma
     */
    public Grade_Extensão_Turma() {
        tamanho();
        alterarTítulos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grade_Extensão_Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Grade_Extensão_Turma().setVisible(true);
            }
        });
    }
    
    private void tamanho(){
        this.setMinimumSize(super.getSize());
    }
    
    private void alterarTítulos(){
        super.título.setText("GRADE");
        super.label_1.setText("Disciplina:");
        super.label_2.setText("Série:");
        super.label_3.setText("Curso:");
        super.label_4.setText("Carga Horária:");
        super.turmasInseridas.setText("GRADES INSERIDAS");
        
        
        tabelaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Disciplina", "Série", "Curso", "Carga Horária"}
        ));
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
